##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
##########

##########
# URL VARIABLES
url: "https://juanbardina.github.io"
baseurl: "/Kiki"
source-code: "https://github.com/juanbardina/Kiki"

##########
# SITE SETTINGS
title: "Reagan-Bush Era Punk Poster Archive"
tagline: "Visual Politics and DIY Aesthetics (1980-1992)"
description: "A digital collection of political punk posters and flyers from the Reagan and Bush administrations."
keywords: "punk; reagan; bush; political posters; archives; DIY"
author: "Juan Bardina"

##########
# COLLECTION SETTINGS
# Your CSV file in the _data folder must be named 'posters.csv'
metadata: "posters"

##########
# ORGANIZATION SETTINGS
organization-name: "Stanford Digital Humanities Archive"
organization-link: "https://history.stanford.edu/"
organization-logo-banner: ""
organization-logo-nav: ""

##########
# ROBOTS EXCLUDE
# noindex: true 

##########
# BUILD SETTINGS 
lib-assets: "/assets/lib"
exclude: [docs/, Rakefile, rakelib/, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
sass:
  style: compressed
